<?php
$title = 'Enter password - ' . $this->zfcUserDisplayName($user);
$this->escapeHtml($title);
$this->headTitle($title);
$form->prepare();
?>
<h2><?php echo $title; ?></h2>
<br/>
<?php echo $this->form()->openTag($form); ?>
<dl class="zend_form">
    <dt><?php echo $this->formLabel($form->get('newCredential')); ?></dt>
    <dd><?php echo $this->formInput($form->get('newCredential')) . $this->formElementErrors($form->get('newCredential')); ?></dd>

    <dt><?php echo $this->formLabel($form->get('newCredentialVerify')); ?></dt>
    <dd><?php echo $this->formInput($form->get('newCredentialVerify')) . $this->formElementErrors($form->get('newCredentialVerify')); ?></dd>
    <dd><?php echo $this->formInput($form->get('submit')); ?></dd>
</dl>
<?php echo $this->form()->closeTag(); ?>